version: "3.9"

services:
    database:
        image: registry.gitlab.com/???:production
        restart: always
        volumes:
            - "${DATA_FOLDER}/database:/var/lib/mysql/"
        environment:
            MYSQL_HOST: database
            MYSQL_USER: "${PROJECT_NAME}"
            MYSQL_DATABASE: "${PROJECT_NAME}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    web-server:
        image: registry.gitlab.com/???:production
        restart: always
        depends_on:
            - database
        ports:
            - 80:80
        environment:
            MYSQL_HOST: database
            MYSQL_USER: ${PROJECT_NAME}
            MYSQL_DATABASE: ${PROJECT_NAME}
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    view-service:
        image: registry.gitlab.com/???:production
        restart: always
        # Delay does not work for local development i.e. with Docker Compose, but will work fine in a Docker Swarm.
        deploy:
            restart_policy:
                condition: any
                delay: 1m
        depends_on:
            - database
        environment:
            MYSQL_HOST: database
            MYSQL_USER: ${PROJECT_NAME}
            MYSQL_DATABASE: ${PROJECT_NAME}
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: "${MYSQL_PASSWORD}"