# Go through all of the stages
stages:
    - containerize
    - deploy

# The containerize stage takes all of the files from the build stage and bundles them into a docker image
containerize:
    stage: containerize
    image: docker:latest
    services:
        - docker:dind
    only:
        - staging
        - production
    script:
        - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
        - mkdir image
        - docker save $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME > image/app.tar
    artifacts:
        paths:
            - image

# The deploy stage deploys the docker image to this projects gitlab registry
deploy:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    only:
        - staging
        - production
    script:
        - docker load -i image/app.tar
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
        - echo "Tell the world that a new image is available"